### ISSUE TITLE
tzdata crashes with argument error in 1.0.1, but not 1.0.0

### ISSUE THREAD

**Issue by hykw** [bitwalker/timex#120]
timex version 1.0.1 crashes with argument error.
Because version 1.0.0 works correctly, there should be some issue between the versions.

## version 1.0.1
```
iex(1)> use Timex
nil
iex(2)> Date.local
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:tzdata_current_release, :release_version)
             lib/tzdata/release_reader.ex:41: Tzdata.ReleaseReader.current_release_from_table/0
             lib/tzdata/release_reader.ex:13: Tzdata.ReleaseReader.simple_lookup/1
             lib/tzdata/release_reader.ex:7: Tzdata.ReleaseReader.zone_and_link_list/0
             lib/tzdata.ex:61: Tzdata.zone_exists?/1
             lib/timezone/timezone.ex:117: Timex.Timezone.get/2
             lib/date/date.ex:171: Timex.Date.local/0
```

## version 1.0.0
```
iex(1)> use Timex
nil
iex(2)> Date.local
%Timex.DateTime{calendar: :gregorian, day: 10, hour: 18, minute: 38, month: 2,
 ms: 738, second: 20,
 timezone: %Timex.TimezoneInfo{abbreviation: "JST",
  from: {:saturday, {{1951, 9, 8}, {1, 0, 0}}}, full_name: "Asia/Tokyo",
  offset_std: 0, offset_utc: 540, until: :max}, year: 2016}
```

The os is CentOS 6.7, and my /etc/sysconfig/clock is the following(just in case):
```
ZONE="Asia/Tokyo"
```

**Comment by bitwalker** [comment]
That error usually occurs when `tzdata` isn't started with `timex`, what does your mix.exs look like?

**Comment by hykw** [comment]
Thank you for your suggestion.The issue fixed with adding `:tzdata` into appliation in mix.exs like below:

```
def application do                                                                                                                                                                                                                           [mod: {Hello, []},
  applications: [
    :phoenix, :phoenix_html, :cowboy, :logger, :gettext,
    :phoenix_ecto, :mariaex,

    :tzdata,   #<======= here
  ],
]
end
```

**Comment by aarvay** [comment]
Hey @bitwalker this error still persists.
Its wierd that this error crept in all of a sudden when no changes were made.
I'm basically trying to set a default value to a field in Ecto.Schema with Timex.now(tz) which was working and now erroring out with the same message. Adding `:tzdata` to application list didn't help either. A hacky workaround I came up with was adding `{:ok, _} = Application.ensure_all_started :timex` at top of the ecto schema file.

Is there a non-hacky fix for this? Why would all apps not be started before the phoenix app starts?

**Comment by bitwalker** [comment]
@aarvay Well, that's not actually a "hack", that's what you have to do in order to execute code at compile-time, which is what you are doing when setting the default value for the schema. All you need in your applications list is `:timex` by the way, as it has `:tzdata` in it's own applications list, but in any case, that's not the issue here, as your application is not started when compiling itself, which is why this error occurs, and why you need to explicitly start the application for use during compilation.

**Comment by aarvay** [comment]
@bitwalker Thanks for getting back. What I couldn't figure out was why this error started occurring all of a sudden when no change was actually made before and after it started to.

**Comment by bitwalker** [comment]
@aarvay Based on the fix you described, it sounds like this is happening at compile time, I don't see how this could have worked with no code changes. Perhaps it was a change in how Ecto handles defaults? I don't have enough context to say with certainty, but those are basically the options. This error can only occur when the `:tzdata` application isn't started, and if you have `:timex` in your applications list, then `:tzdata` will definitely be running before your application starts. If this is happening at compile-time, then this behaviour is expected, since applications are not started during compilation (unless you explicitly do so like in your described solution).
